name: payflow
description: Organize seus boletos

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  get: ^4.1.4
  flutter_screenutil: ^5.0.0+2
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/